modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT/ARR - see LICENSE file"

[[mods]]
modId = "applewoodrebarked"
version = "${version}"
displayName = "[Let's Do Addon] Apple Wood Rebarked"
author = "Awoolanche"
former_author = "MissLilitu"

description = '''
Do you miss the good, old Apple Wood add-on? Apple Wood Rebarked brings it back better than ever! This mod is a rework designed to bring all the features of its successor into the 1.21.1 version, while improving certain aspects and adding new, exciting content. Enjoy beautiful apple-themed furniture, new tools, decorations and extended compatibility with your favorite [Let's Do] mods.

At its current state, Apple Wood Rebarked ports all the blocks and features from the original Apple Wood add-on and adds few features from my other, unreleased projects that were adjusted to fit the overall [Let's Do] aesthetic and vibe. Be aware, that this mod is my playground - things may be added, changed or removed in future releases. Here be dragons.

Big thanks to:
Satisfy - for all the work on the [Let's Do] series,
MissLilitu - for creating the original Apple Wood add-on,
Chaperie - for putting up with my stupid questions about modding,
Everyone who thoroughly playtested the alpha release,
You - for playing my mod!
'''
logoFile = "assets/applewoodrebarked/pack.png"

[[dependencies.applewoodrebarked]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.applewoodrebarked]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.applewoodrebarked]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "applewoodrebarked.mixins.json"
